<?php
/**
 * Author: Yuri Efimov
 * User: octopus
 * Date: 5/29/2016
 * Time: 10:52 AM
 * Filename: Transaction.php
 */

namespace Btcc\Models;

use Btcc\Models\Transaction\BaseTransaction;

/**
 * Class CalculationTransaction
 *
 * This Class should be used on from Calculations Service (or Helper or ServiceProvider)
 *
 *
 * @package app\Models
 * Btcc\Models\Transaction
 * @property integer $id
 * @property integer $user_id
 * @property integer $amount
 * @property integer $type
 * @property integer $status
 * @property integer $sender
 * @property integer $reciever
 * @property boolean $debit_flag
 * @property string  $comment
 * @property string  $hash
 * @property boolean $credit_flag
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 * @property-read \Btcc\Models\User $recieverUser
 * @property-read \Btcc\Models\User $senderUser
 * @method static \Illuminate\Database\Query\Builder|\Btcc\Models\UserTransaction whereId($value)
 * @method static \Illuminate\Database\Query\Builder|\Btcc\Models\UserTransaction whereUserId($value)
 * @method static \Illuminate\Database\Query\Builder|\Btcc\Models\UserTransaction whereAmount($value)
 * @method static \Illuminate\Database\Query\Builder|\Btcc\Models\UserTransaction whereType($value)
 * @method static \Illuminate\Database\Query\Builder|\Btcc\Models\UserTransaction whereStatus($value)
 * @method static \Illuminate\Database\Query\Builder|\Btcc\Models\UserTransaction whereSender($value)
 * @method static \Illuminate\Database\Query\Builder|\Btcc\Models\UserTransaction whereReciever($value)
 * @method static \Illuminate\Database\Query\Builder|\Btcc\Models\UserTransaction whereDebitFlag($value)
 * @method static \Illuminate\Database\Query\Builder|\Btcc\Models\UserTransaction whereCreditFlag($value)
 * @method static \Illuminate\Database\Query\Builder|\Btcc\Models\UserTransaction whereComment($value)
 * @method static \Illuminate\Database\Query\Builder|\Btcc\Models\UserTransaction whereHash($value)
 * @method static \Illuminate\Database\Query\Builder|\Btcc\Models\UserTransaction whereCreatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\Btcc\Models\UserTransaction whereUpdatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\Btcc\Models\Transaction\BaseTransaction ofType($type)
 * @method static \Illuminate\Database\Query\Builder|\Btcc\Models\Transaction\BaseTransaction processed()
 * @mixin \Eloquent
 * @property-read \Btcc\Models\User $parentUser
 * @property integer $sender_id
 * @property integer $reciever_id
 * @method static \Illuminate\Database\Query\Builder|\Btcc\Models\UserTransaction whereSenderId($value)
 * @method static \Illuminate\Database\Query\Builder|\Btcc\Models\UserTransaction whereRecieverId($value)
 */
class CalculationTransaction extends BaseTransaction {

 

  

    public static function totalAmount()
    {
        return static::sum('amount'); // TODO: Change the autogenerated stub
    }

}