<?php
/**
 * Author: Yuri Efimov
 * User: octopus
 * Date: 5/29/2016
 * Time: 10:52 AM
 * Filename: Transaction.php
 */

namespace Btcc\Models;

use Btcc\Models\Transaction\BaseTransaction;

/**
 * Class Transaction
 * @package app\Models
 * Btcc\Models\Transaction
 * @property integer $id
 * @property integer $user_id
 * @property integer $amount
 * @property integer $type
 * @property integer $status
 * @property integer $sender
 * @property integer $reciever
 * @property boolean $debit_flag
 * @property string  $comment
 * @property string  $hash
 */
class Transaction extends BaseTransaction {

    protected $table = 'users_transactions';


    public static function totalAmount()
    {
        return static::sum('amount'); // TODO: Change the autogenerated stub
    }

}