<?php

namespace Btcc\Models;

use Btcc\Models\Profile;
use Btcc\Models\Temp\UserLevel;
use Btcc\Models\Wallet;

use Btcc\Traits\UserHierachiable;
use Illuminate\Auth\Authenticatable;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

/**
 * Btcc\Models\User
 * @property integer                   $id
 * @property string                    $name
 * @property string                    $email
 * @property string                    $password
 * @property string                    $remember_token
 * @property \Carbon\Carbon            $created_at
 * @property \Carbon\Carbon            $updated_at
 * @property-read \Btcc\Models\Profile $profile
 * @property-read \Btcc\Models\Wallet  $wallet
 * @method static \Illuminate\Database\Query\Builder|\Btcc\Models\User whereId($value)
 * @method static \Illuminate\Database\Query\Builder|\Btcc\Models\User whereName($value)
 * @method static \Illuminate\Database\Query\Builder|\Btcc\Models\User whereEmail($value)
 * @method static \Illuminate\Database\Query\Builder|\Btcc\Models\User wherePassword($value)
 * @method static \Illuminate\Database\Query\Builder|\Btcc\Models\User whereRememberToken($value)
 * @method static \Illuminate\Database\Query\Builder|\Btcc\Models\User whereCreatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\Btcc\Models\User whereUpdatedAt($value)
 * @mixin \Eloquent
 */
class User extends \Baum\Node implements AuthenticatableContract, AuthorizableContract, CanResetPasswordContract {
    use Authenticatable, Authorizable, CanResetPassword;

    use UserHierachiable;

    /**
     * The attributes that are mass assignable.
     * @var array
     */
    protected $fillable
        = [
            'name',
            'email',
            'password',
            'binary_position'
        ];

    /**
     * The attributes that should be hidden for arrays.
     * @var array
     */
    protected $hidden
        = [
            'password',
            'remember_token',
        ];

    public function profile()
    {
        return $this->hasOne(Profile::class);
    }

    public function wallet()
    {
        return $this->hasOne(Wallet::class);
    }

    public function invitesIssued()
    {
        return $this->hasMany(Invite::class);
    }

    public function transactionsSent()
    {
        return $this->hasMany(Transaction::class, 'sender');
    }

    public function transactionsRecieved()
    {
        return $this->hasMany(Transaction::class, 'reciever');
    }

    public function binaryTree()
    {
        return $this->hasMany(UserBinaryTree::class,'parent_id','id');
    }


    /**
     * @return User
     */
    public function parent()
    {
        return parent::parent(); // TODO: Change the autogenerated stub
    }



}
